src/Entity/Evenement.php
<?php

namespace App\Entity;
use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Veullez inserer le nom")
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @Assert\NotBlank(message="Veullez inserer la capacité")
     * @ORM\Column(type="integer")
     */
    private $Capacite;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @Assert\NotBlank
     * (message="Veullez inserer une description")
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    /**
     * @Assert\NotBlank
     * (message="Veullez inserer une Adresse")
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;
    /**
     * @return mixed
     */
    public function getid()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setid($id): void
    {
        $this->id = $id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getCapacite(): ?int
    {
        return $this->Capacite;
    }

    public function setCapacite(int $Capacite): self
    {
        $this->Capacite = $Capacite;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(string $Image)
    {
        $this->Image = $Image;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\DomCrawler\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('Nom')
            ->add('Capacite')
            ->add('Date')
            ->add('Description')
            ->add('Image',FileType::class,[
                'label'=>'Image Evenement',
                'mapped'=> false])
            ->add('Adresse')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Knp\Component\Pager\PaginatorInterface ;
use Symfony\Component\HttpFoundation\File\File;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Component\Form\FormBuilderInterface;




class EvenementController extends AbstractController
{
    /**
     * @Route("/evenement", name="evenement")
     */
    public function index(): Response
    {
        return $this->render('evenement/index.html.twig', [
            'controller_name' => 'EvenementController',
        ]);
    }
    /**
     * @Route("/EvSalle", name="EvSalle")
     */
    public function EvSalle(Request $request){
        $repository=$this->getDoctrine()->getRepository(Evenement::class);
        $Evenement=$repository->findAll();

        return $this->render('evenement/AfficheEFront.html.twig',
            ['ev'=>$Evenement]);
    }
    /**
     * @Route("/afficheE", name="afficheE")
     */
    public function afficheEvenement(Request $request): Response
    {   //récuperer le repository pour utiliser la fonction findall
        $Evenement=$this->getDoctrine()->getRepository(Evenement::class)->findAll();

        return $this->render('evenement/afficheE.html.twig', [
            'e' => $Evenement
        ]);
    }

    /**
     * @Route("/ajoutE/", name="ajoutE")
     */
    public function ajoutE(Request  $request): Response
    {   //Création du formulaire
        $e=new Evenement();
        $form=$this->createForm(EvenementType::class,$e);
        //recupérer les données saisies depuis la requete http
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {   $em=$this->getDoctrine()->getManager();
            $uploadedFile = $form['Image']->getData();
            $fileName=md5(uniqid()).'.'.$uploadedFile->guessExtension();
            try {
                $uploadedFile->move(
                    $this->getParameter('Uploads_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
            $e->setImage($fileName);
            $em->persist($e);
            $em->flush();
            return $this->redirectToRoute('afficheE');

        }
        return $this->render('evenement/ajoutE.html.twig', [
            'f' => $form->createView(),
        ]);
    }

    /**
     * @Route("/supp/{id}", name="suppE")
     */
    public function supp($id): Response
    {   //récuperer le classroom à supprimer en utilisant la fonction find($id)
        $Evenement=$this->getDoctrine()->getRepository(Evenement::class)->find($id);
        $em=$this->getDoctrine()->getManager();
        //on passe à la supression
        $em->remove($Evenement);
        // pour que la suppression soit faite au niveau de la base de donnée
        $em->flush();
        return $this->redirectToRoute( 'afficheE');
    }

    /**
     * @Route("/modifE/{id}", name="modifE")
     */
    public function modifE(Request $request,$id)
    {
//je récupère la classe à modifier
        $Evenement=$this->getDoctrine()
            ->getRepository(Evenement::class)->find($id);
//récupération du formulaire
        $form = $this->createForm(EvenementType::class, $Evenement);
//récupérer les données saisies dans les champs
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('afficheE');
        }
        return $this->render("evenement/ajoutE.html.twig",
            array('f'=>$form->createView()));


    }

}

templates/evenement/AfficheEFront.html.twig
{% extends 'base-front.html.twig' %}

{% block body %}


    {%  for i in ev %}
        <img src="{{ asset('uploads/' ~ i.image ) }}" alt="My Image" class="myImage" style="max-height: 300px; max-width: 380px;">
        <h3  style="text-align: center">{{i.nom}}</h3>
        <a class="btn btn-danger" href="{{ path('ajoutR') }}"> Réserver </a>
        <h4 style="text-align: center">{{ i.getDate()|date('d-m-Y H:i:s') }}</h4>
        <h4 style="text-align: center">{{i.Description}}</h4>
        <br> </br>


    {% endfor %}


{% endblock %}

templates/evenement/afficheE.html.twig
{% extends 'base-back.html.twig' %}

{% block body %}

    <table class="table mb-0">
        <div style="margin-left:1250px;">
            <a class="btn btn-info" href="{{path('ajoutE')}}"> Ajouter un Event </a>
        </div>
        <tr>
            <td>
                ID
            </td>
            <td>
                Nom
            </td>
            <td>
                Capacite
            </td>
            <td>
                Date
            </td>
            <td>
                Description
            </td>
            <td>
                Image
            </td>
            <td>
                Adresse
            </td>
        </tr>
        {%  for i in e %}
            <tr>

                <td>
                    {{ i.id }}
                </td>
                <td>
                    {{ i.Nom }}
                </td>
                <td>
                    {{ i.Capacite}}
                </td>
                <td>
                    {{ i.getDate()|date('d-m-Y') }}
                </td>

                <td>
                    {{ i.Description}}
                </td>
                <td><img src="{{ asset('/uploads/' ~ i.Image ) }}" alt="img" class="image" style="max-height: 180px; width: 150px;" ></td>

                <td>
                    {{ i.Adresse}}
                </td>

                <td>
                    <form action="{{ path('ajoutE',{'id':i.id}) }}">
                        <button>Ajouter</button>
                    </form>
                </td>

                <td>
                    <form action="{{ path('suppE',{'id':i.id}) }}">
                        <button>Supprimer</button>
                    </form>
                </td>
                <td>
                    <form action="{{ path('modifE',{'id':i.id}) }}">
                        <button>modifier</button>
                    </form>
                </td>


            </tr>
        {% endfor %}

    </table>
{% endblock %}

templates/evenement/ajoutE.html.twig
{% extends 'base-back.html.twig' %}
{% block body %}

    <div class="app-content">

    <div class="side-app">

    <div class="row">
    <div class="col-md-12">
        <div class="card m-b-20">
            <div class="card-header">
                <h3 class="card-title">Ajouter un évenement</h3>

            </div>
            {{ form_start(f,{'attr' : {'novalidate' : 'novalidate'}})}}
            <div class="card-body">


                    <div class="form-group">
                        <label class="form-label" for="exampleInputname">Nom</label>
                        {{ form_widget(f.Nom, {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Nom'}}) }}
                        {{ form_errors(f.Nom) }}
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="exampleInputname">Capacité</label>
                        {{ form_widget(f.Capacite) }}
                        {{ form_errors(f.Capacite) }}
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="exampleInputEmail2">Date</label>
                        {{ form_widget(f.Date , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Date'}} ) }}
                        {{ form_errors(f.Date) }}

                    </div>
                    <div class="form-group">
                        <label class="form-label" for="exampleInputEmail2">Image</label>
                        {{ form_widget(f.Image, {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Image'}} ) }}

                    </div>
                    <div class="form-group">
                        <label class="form-label" for="exampleInputEmail2">Adresse</label>
                        {{ form_widget(f.Adresse , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Adresse'}} ) }}
                        {{ form_errors(f.Adresse) }}

                    </div>

                    <div class="form-group">
                        <label class="form-label" for="exampleInputEmail2">Description</label>
                        {{ form_widget(f.Description , {'attr': {'class': 'form-control form-control-user' , 'placeholder' : 'Description'}} ) }}
                        {{ form_errors(f.Description) }}

                    </div>


                    <div class="form-group mb-0">
                        <div class="checkbox checkbox-secondary">
                            {{ form_widget(f) }}
                            <button id="checkout-button" type="submit" class="btn btn-success " ><i class="fe fe-check mr-2"></i>Ajouter</button>
                        </div>
                    </div>
                    {% for message in app.flashes('success') %}
                        <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <i class="fa fa-check-circle-o mr-2" aria-hidden="true"></i>{{ message }}
                        </div>
                    {% endfor %}

            </div>
            {{ form_end(f) }}
        </div>
    </div>

    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript"></script>

{% endblock %}

templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EvenementController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/firas/FirstProject/src/Controller/EvenementController.php'|file_link(0) }}">src/Controller/EvenementController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/firas/FirstProject/templates/evenement/index.html.twig'|file_link(0) }}">templates/evenement/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}